version: 1
validation: sovereign
genesis:
  app_state:
    staking:
      params:
        bond_denom: "uvna"
accounts:
  - name: alice
    coins:
      - 200000000uvna
  - name: bob
    coins:
      - 100000000uvna
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
    - 100000uvna
validators:
  - name: alice
    bonded: 100000000uvna
