// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: verana/perm/v1/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Permission types
type PermissionType int32

const (
	PermissionType_UNSPECIFIED      PermissionType = 0
	PermissionType_ISSUER           PermissionType = 1
	PermissionType_VERIFIER         PermissionType = 2
	PermissionType_ISSUER_GRANTOR   PermissionType = 3
	PermissionType_VERIFIER_GRANTOR PermissionType = 4
	PermissionType_ECOSYSTEM        PermissionType = 5
	PermissionType_HOLDER           PermissionType = 6
)

var PermissionType_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "ISSUER",
	2: "VERIFIER",
	3: "ISSUER_GRANTOR",
	4: "VERIFIER_GRANTOR",
	5: "ECOSYSTEM",
	6: "HOLDER",
}

var PermissionType_value = map[string]int32{
	"UNSPECIFIED":      0,
	"ISSUER":           1,
	"VERIFIER":         2,
	"ISSUER_GRANTOR":   3,
	"VERIFIER_GRANTOR": 4,
	"ECOSYSTEM":        5,
	"HOLDER":           6,
}

func (x PermissionType) String() string {
	return proto.EnumName(PermissionType_name, int32(x))
}

func (PermissionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd0a3e5374928bd3, []int{0}
}

// Validation process states
type ValidationState int32

const (
	ValidationState_VALIDATION_STATE_UNSPECIFIED ValidationState = 0
	ValidationState_PENDING                      ValidationState = 1
	ValidationState_VALIDATED                    ValidationState = 2
	ValidationState_TERMINATED                   ValidationState = 3
	ValidationState_TERMINATION_REQUESTED        ValidationState = 4
)

var ValidationState_name = map[int32]string{
	0: "VALIDATION_STATE_UNSPECIFIED",
	1: "PENDING",
	2: "VALIDATED",
	3: "TERMINATED",
	4: "TERMINATION_REQUESTED",
}

var ValidationState_value = map[string]int32{
	"VALIDATION_STATE_UNSPECIFIED": 0,
	"PENDING":                      1,
	"VALIDATED":                    2,
	"TERMINATED":                   3,
	"TERMINATION_REQUESTED":        4,
}

func (x ValidationState) String() string {
	return proto.EnumName(ValidationState_name, int32(x))
}

func (ValidationState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fd0a3e5374928bd3, []int{1}
}

type Permission struct {
	Id         uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SchemaId   uint64         `protobuf:"varint,2,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	Type       PermissionType `protobuf:"varint,3,opt,name=type,proto3,enum=verana.perm.v1.PermissionType" json:"type,omitempty"`
	Did        string         `protobuf:"bytes,4,opt,name=did,proto3" json:"did,omitempty"`
	Authority  string         `protobuf:"bytes,5,opt,name=authority,proto3" json:"authority,omitempty"`
	Created    *time.Time     `protobuf:"bytes,6,opt,name=created,proto3,stdtime" json:"created,omitempty"`
	CreatedBy  string         `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Adjusted   *time.Time     `protobuf:"bytes,8,opt,name=adjusted,proto3,stdtime" json:"adjusted,omitempty"`
	AdjustedBy string         `protobuf:"bytes,9,opt,name=adjusted_by,json=adjustedBy,proto3" json:"adjusted_by,omitempty"`
	// NEW: Slashing related fields
	Slashed   *time.Time `protobuf:"bytes,10,opt,name=slashed,proto3,stdtime" json:"slashed,omitempty"`
	SlashedBy string     `protobuf:"bytes,11,opt,name=slashed_by,json=slashedBy,proto3" json:"slashed_by,omitempty"`
	Repaid    *time.Time `protobuf:"bytes,12,opt,name=repaid,proto3,stdtime" json:"repaid,omitempty"`
	RepaidBy  string     `protobuf:"bytes,13,opt,name=repaid_by,json=repaidBy,proto3" json:"repaid_by,omitempty"`
	// END NEW
	EffectiveFrom    *time.Time `protobuf:"bytes,14,opt,name=effective_from,json=effectiveFrom,proto3,stdtime" json:"effective_from,omitempty"`
	EffectiveUntil   *time.Time `protobuf:"bytes,15,opt,name=effective_until,json=effectiveUntil,proto3,stdtime" json:"effective_until,omitempty"`
	Modified         *time.Time `protobuf:"bytes,16,opt,name=modified,proto3,stdtime" json:"modified,omitempty"`
	ValidationFees   uint64     `protobuf:"varint,17,opt,name=validation_fees,json=validationFees,proto3" json:"validation_fees,omitempty"`
	IssuanceFees     uint64     `protobuf:"varint,18,opt,name=issuance_fees,json=issuanceFees,proto3" json:"issuance_fees,omitempty"`
	VerificationFees uint64     `protobuf:"varint,19,opt,name=verification_fees,json=verificationFees,proto3" json:"verification_fees,omitempty"`
	Deposit          uint64     `protobuf:"varint,20,opt,name=deposit,proto3" json:"deposit,omitempty"`
	// NEW: Slashing deposit fields
	SlashedDeposit uint64 `protobuf:"varint,21,opt,name=slashed_deposit,json=slashedDeposit,proto3" json:"slashed_deposit,omitempty"`
	RepaidDeposit  uint64 `protobuf:"varint,22,opt,name=repaid_deposit,json=repaidDeposit,proto3" json:"repaid_deposit,omitempty"`
	// END NEW
	Revoked            *time.Time      `protobuf:"bytes,23,opt,name=revoked,proto3,stdtime" json:"revoked,omitempty"`
	RevokedBy          string          `protobuf:"bytes,24,opt,name=revoked_by,json=revokedBy,proto3" json:"revoked_by,omitempty"`
	Country            string          `protobuf:"bytes,25,opt,name=country,proto3" json:"country,omitempty"`
	ValidatorPermId    uint64          `protobuf:"varint,26,opt,name=validator_perm_id,json=validatorPermId,proto3" json:"validator_perm_id,omitempty"`
	VpState            ValidationState `protobuf:"varint,27,opt,name=vp_state,json=vpState,proto3,enum=verana.perm.v1.ValidationState" json:"vp_state,omitempty"`
	VpExp              *time.Time      `protobuf:"bytes,28,opt,name=vp_exp,json=vpExp,proto3,stdtime" json:"vp_exp,omitempty"`
	VpLastStateChange  *time.Time      `protobuf:"bytes,29,opt,name=vp_last_state_change,json=vpLastStateChange,proto3,stdtime" json:"vp_last_state_change,omitempty"`
	VpValidatorDeposit uint64          `protobuf:"varint,30,opt,name=vp_validator_deposit,json=vpValidatorDeposit,proto3" json:"vp_validator_deposit,omitempty"`
	VpCurrentFees      uint64          `protobuf:"varint,31,opt,name=vp_current_fees,json=vpCurrentFees,proto3" json:"vp_current_fees,omitempty"`
	VpCurrentDeposit   uint64          `protobuf:"varint,32,opt,name=vp_current_deposit,json=vpCurrentDeposit,proto3" json:"vp_current_deposit,omitempty"`
	VpSummaryDigestSri string          `protobuf:"bytes,33,opt,name=vp_summary_digest_sri,json=vpSummaryDigestSri,proto3" json:"vp_summary_digest_sri,omitempty"`
	VpTermRequested    *time.Time      `protobuf:"bytes,34,opt,name=vp_term_requested,json=vpTermRequested,proto3,stdtime" json:"vp_term_requested,omitempty"`
	// Fee discount fields (scaled: 0 = 0.0, 10000 = 1.0, range 0-10000)
	// Per Issue #94: spec merged exemption and discount into single *_fee_discount field
	IssuanceFeeDiscount     uint64 `protobuf:"varint,35,opt,name=issuance_fee_discount,json=issuanceFeeDiscount,proto3" json:"issuance_fee_discount,omitempty"`
	VerificationFeeDiscount uint64 `protobuf:"varint,36,opt,name=verification_fee_discount,json=verificationFeeDiscount,proto3" json:"verification_fee_discount,omitempty"`
	// VS Operator fields (spec v4)
	VsOperator                   string                                   `protobuf:"bytes,37,opt,name=vs_operator,json=vsOperator,proto3" json:"vs_operator,omitempty"`
	VsOperatorAuthzEnabled       bool                                     `protobuf:"varint,38,opt,name=vs_operator_authz_enabled,json=vsOperatorAuthzEnabled,proto3" json:"vs_operator_authz_enabled,omitempty"`
	VsOperatorAuthzSpendLimit    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,39,rep,name=vs_operator_authz_spend_limit,json=vsOperatorAuthzSpendLimit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"vs_operator_authz_spend_limit"`
	VsOperatorAuthzWithFeegrant  bool                                     `protobuf:"varint,40,opt,name=vs_operator_authz_with_feegrant,json=vsOperatorAuthzWithFeegrant,proto3" json:"vs_operator_authz_with_feegrant,omitempty"`
	VsOperatorAuthzFeeSpendLimit github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,41,rep,name=vs_operator_authz_fee_spend_limit,json=vsOperatorAuthzFeeSpendLimit,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"vs_operator_authz_fee_spend_limit"`
	VsOperatorAuthzSpendPeriod   *time.Duration                           `protobuf:"bytes,42,opt,name=vs_operator_authz_spend_period,json=vsOperatorAuthzSpendPeriod,proto3,stdduration" json:"vs_operator_authz_spend_period,omitempty"`
}

func (m *Permission) Reset()         { *m = Permission{} }
func (m *Permission) String() string { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()    {}
func (*Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd0a3e5374928bd3, []int{0}
}
func (m *Permission) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Permission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Permission.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Permission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Permission.Merge(m, src)
}
func (m *Permission) XXX_Size() int {
	return m.Size()
}
func (m *Permission) XXX_DiscardUnknown() {
	xxx_messageInfo_Permission.DiscardUnknown(m)
}

var xxx_messageInfo_Permission proto.InternalMessageInfo

func (m *Permission) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Permission) GetSchemaId() uint64 {
	if m != nil {
		return m.SchemaId
	}
	return 0
}

func (m *Permission) GetType() PermissionType {
	if m != nil {
		return m.Type
	}
	return PermissionType_UNSPECIFIED
}

func (m *Permission) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *Permission) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *Permission) GetCreated() *time.Time {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Permission) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Permission) GetAdjusted() *time.Time {
	if m != nil {
		return m.Adjusted
	}
	return nil
}

func (m *Permission) GetAdjustedBy() string {
	if m != nil {
		return m.AdjustedBy
	}
	return ""
}

func (m *Permission) GetSlashed() *time.Time {
	if m != nil {
		return m.Slashed
	}
	return nil
}

func (m *Permission) GetSlashedBy() string {
	if m != nil {
		return m.SlashedBy
	}
	return ""
}

func (m *Permission) GetRepaid() *time.Time {
	if m != nil {
		return m.Repaid
	}
	return nil
}

func (m *Permission) GetRepaidBy() string {
	if m != nil {
		return m.RepaidBy
	}
	return ""
}

func (m *Permission) GetEffectiveFrom() *time.Time {
	if m != nil {
		return m.EffectiveFrom
	}
	return nil
}

func (m *Permission) GetEffectiveUntil() *time.Time {
	if m != nil {
		return m.EffectiveUntil
	}
	return nil
}

func (m *Permission) GetModified() *time.Time {
	if m != nil {
		return m.Modified
	}
	return nil
}

func (m *Permission) GetValidationFees() uint64 {
	if m != nil {
		return m.ValidationFees
	}
	return 0
}

func (m *Permission) GetIssuanceFees() uint64 {
	if m != nil {
		return m.IssuanceFees
	}
	return 0
}

func (m *Permission) GetVerificationFees() uint64 {
	if m != nil {
		return m.VerificationFees
	}
	return 0
}

func (m *Permission) GetDeposit() uint64 {
	if m != nil {
		return m.Deposit
	}
	return 0
}

func (m *Permission) GetSlashedDeposit() uint64 {
	if m != nil {
		return m.SlashedDeposit
	}
	return 0
}

func (m *Permission) GetRepaidDeposit() uint64 {
	if m != nil {
		return m.RepaidDeposit
	}
	return 0
}

func (m *Permission) GetRevoked() *time.Time {
	if m != nil {
		return m.Revoked
	}
	return nil
}

func (m *Permission) GetRevokedBy() string {
	if m != nil {
		return m.RevokedBy
	}
	return ""
}

func (m *Permission) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *Permission) GetValidatorPermId() uint64 {
	if m != nil {
		return m.ValidatorPermId
	}
	return 0
}

func (m *Permission) GetVpState() ValidationState {
	if m != nil {
		return m.VpState
	}
	return ValidationState_VALIDATION_STATE_UNSPECIFIED
}

func (m *Permission) GetVpExp() *time.Time {
	if m != nil {
		return m.VpExp
	}
	return nil
}

func (m *Permission) GetVpLastStateChange() *time.Time {
	if m != nil {
		return m.VpLastStateChange
	}
	return nil
}

func (m *Permission) GetVpValidatorDeposit() uint64 {
	if m != nil {
		return m.VpValidatorDeposit
	}
	return 0
}

func (m *Permission) GetVpCurrentFees() uint64 {
	if m != nil {
		return m.VpCurrentFees
	}
	return 0
}

func (m *Permission) GetVpCurrentDeposit() uint64 {
	if m != nil {
		return m.VpCurrentDeposit
	}
	return 0
}

func (m *Permission) GetVpSummaryDigestSri() string {
	if m != nil {
		return m.VpSummaryDigestSri
	}
	return ""
}

func (m *Permission) GetVpTermRequested() *time.Time {
	if m != nil {
		return m.VpTermRequested
	}
	return nil
}

func (m *Permission) GetIssuanceFeeDiscount() uint64 {
	if m != nil {
		return m.IssuanceFeeDiscount
	}
	return 0
}

func (m *Permission) GetVerificationFeeDiscount() uint64 {
	if m != nil {
		return m.VerificationFeeDiscount
	}
	return 0
}

func (m *Permission) GetVsOperator() string {
	if m != nil {
		return m.VsOperator
	}
	return ""
}

func (m *Permission) GetVsOperatorAuthzEnabled() bool {
	if m != nil {
		return m.VsOperatorAuthzEnabled
	}
	return false
}

func (m *Permission) GetVsOperatorAuthzSpendLimit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.VsOperatorAuthzSpendLimit
	}
	return nil
}

func (m *Permission) GetVsOperatorAuthzWithFeegrant() bool {
	if m != nil {
		return m.VsOperatorAuthzWithFeegrant
	}
	return false
}

func (m *Permission) GetVsOperatorAuthzFeeSpendLimit() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.VsOperatorAuthzFeeSpendLimit
	}
	return nil
}

func (m *Permission) GetVsOperatorAuthzSpendPeriod() *time.Duration {
	if m != nil {
		return m.VsOperatorAuthzSpendPeriod
	}
	return nil
}

type PermissionSession struct {
	Id             string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Authority      string                     `protobuf:"bytes,2,opt,name=authority,proto3" json:"authority,omitempty"`
	VsOperator     string                     `protobuf:"bytes,3,opt,name=vs_operator,json=vsOperator,proto3" json:"vs_operator,omitempty"`
	AgentPermId    uint64                     `protobuf:"varint,4,opt,name=agent_perm_id,json=agentPermId,proto3" json:"agent_perm_id,omitempty"`
	SessionRecords []*PermissionSessionRecord `protobuf:"bytes,5,rep,name=session_records,json=sessionRecords,proto3" json:"session_records,omitempty"`
	Created        *time.Time                 `protobuf:"bytes,6,opt,name=created,proto3,stdtime" json:"created,omitempty"`
	Modified       *time.Time                 `protobuf:"bytes,7,opt,name=modified,proto3,stdtime" json:"modified,omitempty"`
}

func (m *PermissionSession) Reset()         { *m = PermissionSession{} }
func (m *PermissionSession) String() string { return proto.CompactTextString(m) }
func (*PermissionSession) ProtoMessage()    {}
func (*PermissionSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd0a3e5374928bd3, []int{1}
}
func (m *PermissionSession) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PermissionSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PermissionSession.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PermissionSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionSession.Merge(m, src)
}
func (m *PermissionSession) XXX_Size() int {
	return m.Size()
}
func (m *PermissionSession) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionSession.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionSession proto.InternalMessageInfo

func (m *PermissionSession) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PermissionSession) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *PermissionSession) GetVsOperator() string {
	if m != nil {
		return m.VsOperator
	}
	return ""
}

func (m *PermissionSession) GetAgentPermId() uint64 {
	if m != nil {
		return m.AgentPermId
	}
	return 0
}

func (m *PermissionSession) GetSessionRecords() []*PermissionSessionRecord {
	if m != nil {
		return m.SessionRecords
	}
	return nil
}

func (m *PermissionSession) GetCreated() *time.Time {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *PermissionSession) GetModified() *time.Time {
	if m != nil {
		return m.Modified
	}
	return nil
}

type PermissionSessionRecord struct {
	Created           *time.Time `protobuf:"bytes,1,opt,name=created,proto3,stdtime" json:"created,omitempty"`
	IssuerPermId      uint64     `protobuf:"varint,2,opt,name=issuer_perm_id,json=issuerPermId,proto3" json:"issuer_perm_id,omitempty"`
	VerifierPermId    uint64     `protobuf:"varint,3,opt,name=verifier_perm_id,json=verifierPermId,proto3" json:"verifier_perm_id,omitempty"`
	WalletAgentPermId uint64     `protobuf:"varint,4,opt,name=wallet_agent_perm_id,json=walletAgentPermId,proto3" json:"wallet_agent_perm_id,omitempty"`
}

func (m *PermissionSessionRecord) Reset()         { *m = PermissionSessionRecord{} }
func (m *PermissionSessionRecord) String() string { return proto.CompactTextString(m) }
func (*PermissionSessionRecord) ProtoMessage()    {}
func (*PermissionSessionRecord) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd0a3e5374928bd3, []int{2}
}
func (m *PermissionSessionRecord) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PermissionSessionRecord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PermissionSessionRecord.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PermissionSessionRecord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionSessionRecord.Merge(m, src)
}
func (m *PermissionSessionRecord) XXX_Size() int {
	return m.Size()
}
func (m *PermissionSessionRecord) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionSessionRecord.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionSessionRecord proto.InternalMessageInfo

func (m *PermissionSessionRecord) GetCreated() *time.Time {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *PermissionSessionRecord) GetIssuerPermId() uint64 {
	if m != nil {
		return m.IssuerPermId
	}
	return 0
}

func (m *PermissionSessionRecord) GetVerifierPermId() uint64 {
	if m != nil {
		return m.VerifierPermId
	}
	return 0
}

func (m *PermissionSessionRecord) GetWalletAgentPermId() uint64 {
	if m != nil {
		return m.WalletAgentPermId
	}
	return 0
}

// OptionalUInt64 is a wrapper for optional uint64 values
type OptionalUInt64 struct {
	Value uint64 `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *OptionalUInt64) Reset()         { *m = OptionalUInt64{} }
func (m *OptionalUInt64) String() string { return proto.CompactTextString(m) }
func (*OptionalUInt64) ProtoMessage()    {}
func (*OptionalUInt64) Descriptor() ([]byte, []int) {
	return fileDescriptor_fd0a3e5374928bd3, []int{3}
}
func (m *OptionalUInt64) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OptionalUInt64) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OptionalUInt64.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OptionalUInt64) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptionalUInt64.Merge(m, src)
}
func (m *OptionalUInt64) XXX_Size() int {
	return m.Size()
}
func (m *OptionalUInt64) XXX_DiscardUnknown() {
	xxx_messageInfo_OptionalUInt64.DiscardUnknown(m)
}

var xxx_messageInfo_OptionalUInt64 proto.InternalMessageInfo

func (m *OptionalUInt64) GetValue() uint64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterEnum("verana.perm.v1.PermissionType", PermissionType_name, PermissionType_value)
	proto.RegisterEnum("verana.perm.v1.ValidationState", ValidationState_name, ValidationState_value)
	proto.RegisterType((*Permission)(nil), "verana.perm.v1.Permission")
	proto.RegisterType((*PermissionSession)(nil), "verana.perm.v1.PermissionSession")
	proto.RegisterType((*PermissionSessionRecord)(nil), "verana.perm.v1.PermissionSessionRecord")
	proto.RegisterType((*OptionalUInt64)(nil), "verana.perm.v1.OptionalUInt64")
}

func init() { proto.RegisterFile("verana/perm/v1/types.proto", fileDescriptor_fd0a3e5374928bd3) }

var fileDescriptor_fd0a3e5374928bd3 = []byte{
	// 1469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xcb, 0x72, 0x13, 0x47,
	0x17, 0xf6, 0xc8, 0xf2, 0xed, 0x08, 0xeb, 0xd2, 0xd8, 0xd0, 0x32, 0x46, 0x12, 0xe6, 0xa6, 0xdf,
	0xff, 0x8f, 0xf4, 0xdb, 0x09, 0x10, 0x5c, 0xd9, 0x58, 0xd6, 0x98, 0xa8, 0xca, 0xd8, 0x66, 0x24,
	0x3b, 0x95, 0x6c, 0xa6, 0x46, 0x9a, 0xb6, 0xdc, 0x41, 0x73, 0xc9, 0xf4, 0x68, 0x40, 0xac, 0xf2,
	0x08, 0x54, 0x56, 0xc9, 0x1b, 0xa4, 0xb2, 0xca, 0x22, 0x0f, 0xc1, 0x92, 0x62, 0x91, 0xca, 0x2a,
	0xa4, 0x60, 0x91, 0xd7, 0x48, 0x75, 0x4f, 0x8f, 0x35, 0x96, 0xa1, 0x2c, 0x2a, 0x95, 0x8d, 0xd4,
	0x7d, 0xce, 0x77, 0x6e, 0x7d, 0x4e, 0x9f, 0x3e, 0x03, 0x4b, 0x01, 0xf1, 0x0c, 0xdb, 0xa8, 0xba,
	0xc4, 0xb3, 0xaa, 0xc1, 0x5a, 0xd5, 0x1f, 0xb8, 0x84, 0x55, 0x5c, 0xcf, 0xf1, 0x1d, 0x94, 0x0e,
	0x79, 0x15, 0xce, 0xab, 0x04, 0x6b, 0x4b, 0x39, 0xc3, 0xa2, 0xb6, 0x53, 0x15, 0xbf, 0x21, 0x64,
	0xa9, 0xd0, 0x71, 0x98, 0xe5, 0xb0, 0x6a, 0xdb, 0x60, 0xa4, 0x1a, 0xac, 0xb5, 0x89, 0x6f, 0xac,
	0x55, 0x3b, 0x0e, 0xb5, 0x25, 0x3f, 0x1f, 0xf2, 0x75, 0xb1, 0xab, 0x86, 0x1b, 0xc9, 0x5a, 0xe8,
	0x3a, 0x5d, 0x27, 0xa4, 0xf3, 0x55, 0xa4, 0xb0, 0xeb, 0x38, 0xdd, 0x1e, 0xa9, 0x8a, 0x5d, 0xbb,
	0x7f, 0x54, 0x35, 0xfb, 0x9e, 0xe1, 0x53, 0x27, 0x52, 0x58, 0x1c, 0xe5, 0xfb, 0xd4, 0x22, 0xcc,
	0x37, 0x2c, 0x37, 0x04, 0xac, 0xbc, 0xb8, 0x08, 0xb0, 0x4f, 0x3c, 0x8b, 0x32, 0x46, 0x1d, 0x1b,
	0xa5, 0x21, 0x41, 0x4d, 0xac, 0x94, 0x94, 0x72, 0x52, 0x4b, 0x50, 0x13, 0x5d, 0x81, 0x39, 0xd6,
	0x39, 0x26, 0x96, 0xa1, 0x53, 0x13, 0x27, 0x04, 0x79, 0x36, 0x24, 0x34, 0x4c, 0xb4, 0x0e, 0x49,
	0x1e, 0x3f, 0x9e, 0x2c, 0x29, 0xe5, 0xf4, 0x7a, 0xa1, 0x72, 0x3a, 0xfe, 0xca, 0x50, 0x6d, 0x6b,
	0xe0, 0x12, 0x4d, 0x60, 0x51, 0x16, 0x26, 0x4d, 0x6a, 0xe2, 0x64, 0x49, 0x29, 0xcf, 0x69, 0x7c,
	0x89, 0xee, 0xc1, 0x9c, 0xd1, 0xf7, 0x8f, 0x1d, 0x8f, 0xfa, 0x03, 0x3c, 0xc5, 0xe9, 0x35, 0xfc,
	0xfa, 0xd7, 0x3b, 0x0b, 0x32, 0xfa, 0x4d, 0xd3, 0xf4, 0x08, 0x63, 0x4d, 0xdf, 0xa3, 0x76, 0x57,
	0x1b, 0x42, 0xd1, 0x06, 0xcc, 0x74, 0x3c, 0x62, 0xf8, 0xc4, 0xc4, 0xd3, 0x25, 0xa5, 0x9c, 0x5a,
	0x5f, 0xaa, 0x84, 0xc1, 0x56, 0xa2, 0x60, 0x2b, 0xad, 0x28, 0xd8, 0x5a, 0xf2, 0xc5, 0x9b, 0xa2,
	0xa2, 0x45, 0x02, 0xe8, 0x3e, 0x80, 0x5c, 0xea, 0xed, 0x01, 0x9e, 0x39, 0xcf, 0xa8, 0xc4, 0xd6,
	0x06, 0xe8, 0x73, 0x98, 0x35, 0xcc, 0x6f, 0xfa, 0x8c, 0x5b, 0x9d, 0x1d, 0xd3, 0xea, 0x89, 0x04,
	0x7a, 0x00, 0xa9, 0x68, 0xcd, 0xed, 0xce, 0x9d, 0x63, 0x17, 0x22, 0x70, 0x4d, 0x44, 0xcb, 0x7a,
	0x06, 0x3b, 0x26, 0x26, 0x86, 0x71, 0xa3, 0x95, 0x02, 0x3c, 0x5a, 0xb9, 0xe4, 0x56, 0x53, 0xe7,
	0x45, 0x2b, 0xb1, 0xb5, 0x01, 0xfa, 0x0c, 0xa6, 0x3d, 0xe2, 0x1a, 0xd4, 0xc4, 0x17, 0xc6, 0xb4,
	0x29, 0xf1, 0xe8, 0x2e, 0xcc, 0x85, 0x2b, 0x6e, 0x71, 0xfe, 0x1c, 0x8b, 0xb3, 0x21, 0xb4, 0x36,
	0x40, 0x0f, 0x21, 0x4d, 0x8e, 0x8e, 0x48, 0xc7, 0xa7, 0x01, 0xd1, 0x8f, 0x3c, 0xc7, 0xc2, 0xe9,
	0x31, 0x0d, 0xcf, 0x9f, 0xc8, 0x6d, 0x7b, 0x8e, 0x85, 0x1a, 0x90, 0x19, 0x2a, 0xea, 0xdb, 0x3e,
	0xed, 0xe1, 0xcc, 0x98, 0x9a, 0x86, 0x1e, 0x1c, 0x70, 0x39, 0x9e, 0x72, 0xcb, 0x31, 0xe9, 0x11,
	0x25, 0x26, 0xce, 0x8e, 0x9b, 0xf2, 0x48, 0x02, 0xdd, 0x86, 0x4c, 0x60, 0xf4, 0xa8, 0x29, 0x2e,
	0xa5, 0x7e, 0x44, 0x08, 0xc3, 0x39, 0x71, 0x8d, 0xd2, 0x43, 0xf2, 0x36, 0x21, 0x0c, 0x5d, 0x87,
	0x79, 0xca, 0x58, 0xdf, 0xb0, 0x3b, 0x24, 0x84, 0x21, 0x01, 0xbb, 0x10, 0x11, 0x05, 0xe8, 0xbf,
	0x90, 0x0b, 0x88, 0x47, 0x8f, 0x68, 0x27, 0xa6, 0xef, 0xa2, 0x00, 0x66, 0xe3, 0x0c, 0x01, 0xc6,
	0x30, 0x63, 0x12, 0xd7, 0x61, 0xd4, 0xc7, 0x0b, 0x02, 0x12, 0x6d, 0xb9, 0x53, 0x51, 0x41, 0x44,
	0x88, 0xc5, 0xd0, 0x29, 0x49, 0xae, 0x4b, 0xe0, 0x4d, 0x48, 0xcb, 0x34, 0x46, 0xb8, 0x4b, 0x02,
	0x37, 0x1f, 0x52, 0x23, 0xd8, 0x06, 0xcc, 0x78, 0x24, 0x70, 0x9e, 0x10, 0x13, 0x5f, 0x1e, 0xb7,
	0x38, 0xa5, 0x00, 0x2f, 0x4e, 0xb9, 0xe4, 0xa5, 0x82, 0xcf, 0x2b, 0x4e, 0x89, 0xad, 0x0d, 0x78,
	0x78, 0x1d, 0xa7, 0x6f, 0xfb, 0xde, 0x00, 0xe7, 0x45, 0x37, 0x89, 0xb6, 0x68, 0x15, 0x72, 0xf2,
	0x70, 0x1d, 0x4f, 0xe7, 0xdd, 0x88, 0x37, 0xaf, 0x25, 0xe1, 0x78, 0xe6, 0x84, 0xc1, 0xbb, 0x53,
	0xc3, 0x44, 0x1b, 0x30, 0x1b, 0xb8, 0x3a, 0xf3, 0x0d, 0x9f, 0xe0, 0x2b, 0xa2, 0x8f, 0x15, 0x47,
	0xfb, 0xd8, 0xe1, 0x49, 0xa2, 0x9a, 0x1c, 0xa6, 0xcd, 0x04, 0xae, 0x58, 0xa0, 0xfb, 0x30, 0x1d,
	0xb8, 0x3a, 0x79, 0xe6, 0xe2, 0xe5, 0x31, 0xa3, 0x9e, 0x0a, 0x5c, 0xf5, 0x99, 0x8b, 0x1e, 0xc3,
	0x42, 0xe0, 0xea, 0x3d, 0x83, 0xf9, 0xa1, 0x65, 0xbd, 0x73, 0x6c, 0xd8, 0x5d, 0x82, 0xaf, 0x8e,
	0xa9, 0x26, 0x17, 0xb8, 0x3b, 0x06, 0xf3, 0x85, 0x17, 0x5b, 0x42, 0x14, 0xfd, 0x5f, 0xa8, 0x1c,
	0x86, 0x1d, 0xe5, 0xab, 0x20, 0xc2, 0x46, 0x81, 0x7b, 0x18, 0xb1, 0xa2, 0xa4, 0xdd, 0x82, 0x4c,
	0xe0, 0xea, 0x9d, 0xbe, 0xe7, 0x11, 0xdb, 0x0f, 0x2b, 0xa9, 0x18, 0x26, 0x37, 0x70, 0xb7, 0x42,
	0xaa, 0x28, 0xa3, 0xff, 0x01, 0x8a, 0xe1, 0x22, 0xbd, 0x25, 0x59, 0x74, 0x11, 0x34, 0xd2, 0xba,
	0x06, 0x8b, 0xfc, 0x3c, 0xfb, 0x96, 0x65, 0x78, 0x03, 0xdd, 0xa4, 0x5d, 0xc2, 0x83, 0xf4, 0x28,
	0xbe, 0x26, 0x72, 0x84, 0x02, 0xb7, 0x19, 0xf2, 0xea, 0x82, 0xd5, 0xf4, 0x28, 0xda, 0x81, 0x5c,
	0xe0, 0xea, 0x3e, 0xcf, 0x93, 0x47, 0xbe, 0xed, 0x13, 0xd1, 0x5c, 0x57, 0xc6, 0x3c, 0x8a, 0x4c,
	0xe0, 0xb6, 0x88, 0x67, 0x69, 0x91, 0x20, 0x5a, 0x87, 0xc5, 0xf8, 0x3d, 0xd2, 0x4d, 0xca, 0x44,
	0x5d, 0xe0, 0xeb, 0xc2, 0xe3, 0x8b, 0xb1, 0xfb, 0x54, 0x97, 0x2c, 0xb4, 0x01, 0xf9, 0xd1, 0x6b,
	0x35, 0x94, 0xbb, 0x21, 0xe4, 0x2e, 0x8f, 0x5c, 0xaf, 0x13, 0xd9, 0x07, 0x90, 0x0a, 0x98, 0xee,
	0xb8, 0xc4, 0xe3, 0x87, 0x8b, 0x6f, 0x9e, 0xd7, 0xd3, 0x03, 0xb6, 0x27, 0xb1, 0xe8, 0x01, 0xe4,
	0x63, 0xa2, 0x3a, 0x7f, 0xda, 0x9e, 0xeb, 0xc4, 0x36, 0xda, 0x3d, 0x62, 0xe2, 0x5b, 0x25, 0xa5,
	0x3c, 0xab, 0x5d, 0x1a, 0xc2, 0x37, 0x39, 0x5b, 0x0d, 0xb9, 0xe8, 0x7b, 0x05, 0xae, 0x9e, 0x95,
	0x65, 0x2e, 0xb1, 0x4d, 0xbd, 0x47, 0x2d, 0xea, 0xe3, 0xdb, 0xa5, 0xc9, 0x72, 0x6a, 0x3d, 0x5f,
	0x91, 0x5e, 0xf0, 0x89, 0xa3, 0x22, 0x27, 0x8e, 0xca, 0x96, 0x43, 0xed, 0xda, 0xdd, 0x97, 0x7f,
	0x14, 0x27, 0x7e, 0x7e, 0x53, 0x2c, 0x77, 0xa9, 0x7f, 0xdc, 0x6f, 0x57, 0x3a, 0x8e, 0x25, 0x27,
	0x0e, 0xf9, 0x77, 0x87, 0x99, 0x4f, 0xe4, 0x80, 0xc3, 0x05, 0xd8, 0x4f, 0x7f, 0xfd, 0xb2, 0xaa,
	0x68, 0xf9, 0x11, 0x8f, 0x9a, 0xdc, 0xe6, 0x0e, 0x37, 0x89, 0xea, 0x50, 0x3c, 0xeb, 0xd3, 0x53,
	0xea, 0x1f, 0xf3, 0x03, 0xed, 0x7a, 0x86, 0xed, 0xe3, 0xb2, 0x88, 0xea, 0xca, 0x88, 0x8e, 0x2f,
	0xa9, 0x7f, 0xbc, 0x2d, 0x21, 0xe8, 0x47, 0x05, 0xae, 0x9d, 0x55, 0xc3, 0x53, 0x12, 0x0f, 0xef,
	0x3f, 0xff, 0x52, 0x78, 0xcb, 0x23, 0xae, 0x6d, 0x13, 0x12, 0x8b, 0xb0, 0x03, 0x85, 0x0f, 0x9d,
	0xba, 0x4b, 0x3c, 0xea, 0x98, 0x78, 0x55, 0xd4, 0x6d, 0xfe, 0x4c, 0xdd, 0xd6, 0xe5, 0x5c, 0x56,
	0x4b, 0xfe, 0xc0, 0xcb, 0x76, 0xe9, 0x7d, 0xa7, 0xb8, 0x2f, 0x54, 0xac, 0xbc, 0x4e, 0x40, 0x6e,
	0x38, 0x3b, 0x35, 0xc9, 0xe8, 0x64, 0x36, 0x27, 0x26, 0xb3, 0xe5, 0xf8, 0xd8, 0x94, 0x10, 0xe4,
	0xd8, 0x70, 0x54, 0x3c, 0x5d, 0x95, 0x93, 0x82, 0x1f, 0xaf, 0xbd, 0x15, 0x98, 0x37, 0xba, 0xfc,
	0x42, 0x47, 0xfd, 0x31, 0x29, 0xca, 0x3c, 0x25, 0x88, 0xb2, 0x37, 0xee, 0x43, 0x86, 0x85, 0xd6,
	0x75, 0x8f, 0x74, 0x1c, 0xcf, 0x64, 0x78, 0x4a, 0x1c, 0xfb, 0xed, 0x0f, 0x8f, 0x7a, 0xd2, 0x5d,
	0x4d, 0xe0, 0xb5, 0x34, 0x8b, 0x6f, 0xd9, 0x3f, 0x9a, 0xd9, 0xe2, 0xef, 0xf0, 0xcc, 0xc7, 0xbe,
	0xc3, 0x2b, 0xbf, 0x29, 0x70, 0xf9, 0x03, 0x5e, 0xc6, 0xbd, 0x52, 0x3e, 0xd6, 0xab, 0x1b, 0x90,
	0xe6, 0x1d, 0x85, 0x0c, 0x1f, 0x9a, 0xc4, 0xf0, 0xdd, 0x26, 0xd1, 0x2b, 0x53, 0x06, 0xf9, 0x3c,
	0xc7, 0x70, 0x93, 0x72, 0x0c, 0x90, 0x74, 0x89, 0xac, 0xc2, 0xc2, 0x53, 0xa3, 0xd7, 0x23, 0xbe,
	0xfe, 0xbe, 0xf4, 0xe4, 0x42, 0xde, 0xe6, 0x30, 0x49, 0x2b, 0xb7, 0x20, 0xbd, 0xe7, 0xf2, 0xca,
	0x32, 0x7a, 0x07, 0x0d, 0xdb, 0xbf, 0xf7, 0x29, 0x5a, 0x80, 0xa9, 0xc0, 0xe8, 0xf5, 0x89, 0x1c,
	0xe3, 0xc3, 0xcd, 0xea, 0x77, 0x0a, 0xa4, 0x4f, 0x4f, 0xe4, 0x28, 0x03, 0xa9, 0x83, 0xdd, 0xe6,
	0xbe, 0xba, 0xd5, 0xd8, 0x6e, 0xa8, 0xf5, 0xec, 0x04, 0x02, 0x98, 0x6e, 0x34, 0x9b, 0x07, 0xaa,
	0x96, 0x55, 0xd0, 0x05, 0x98, 0x3d, 0x54, 0x35, 0xce, 0xd1, 0xb2, 0x09, 0x84, 0x20, 0x1d, 0x72,
	0xf4, 0x87, 0xda, 0xe6, 0x6e, 0x6b, 0x4f, 0xcb, 0x4e, 0xa2, 0x05, 0xc8, 0x46, 0x88, 0x13, 0x6a,
	0x12, 0xcd, 0xc3, 0x9c, 0xba, 0xb5, 0xd7, 0xfc, 0xaa, 0xd9, 0x52, 0x1f, 0x65, 0xa7, 0xb8, 0xca,
	0x2f, 0xf6, 0x76, 0xea, 0xaa, 0x96, 0x9d, 0x5e, 0x7d, 0x0e, 0x99, 0x91, 0xb7, 0x14, 0x95, 0x60,
	0xf9, 0x70, 0x73, 0xa7, 0x51, 0xdf, 0x6c, 0x35, 0xf6, 0x76, 0xf5, 0x66, 0x6b, 0xb3, 0xa5, 0xea,
	0xa7, 0x7d, 0x4a, 0xc1, 0xcc, 0xbe, 0xba, 0x5b, 0x6f, 0xec, 0x3e, 0xcc, 0x2a, 0x5c, 0xb9, 0x84,
	0xab, 0xf5, 0x6c, 0x02, 0xa5, 0x01, 0x5a, 0xaa, 0xf6, 0xa8, 0xb1, 0x2b, 0xf6, 0x93, 0x28, 0x0f,
	0x8b, 0xd1, 0x9e, 0xab, 0xd3, 0xd4, 0xc7, 0x07, 0x6a, 0x93, 0xb3, 0x92, 0xb5, 0xfa, 0xcb, 0xb7,
	0x05, 0xe5, 0xd5, 0xdb, 0x82, 0xf2, 0xe7, 0xdb, 0x82, 0xf2, 0xe2, 0x5d, 0x61, 0xe2, 0xd5, 0xbb,
	0xc2, 0xc4, 0xef, 0xef, 0x0a, 0x13, 0x5f, 0xaf, 0xc6, 0x1a, 0x44, 0x58, 0xd6, 0x77, 0x7a, 0x46,
	0x9b, 0xc9, 0x75, 0xf5, 0x59, 0xf8, 0xad, 0x27, 0x1a, 0x45, 0x7b, 0x5a, 0x14, 0xc4, 0x27, 0x7f,
	0x07, 0x00, 0x00, 0xff, 0xff, 0xfe, 0x31, 0x24, 0xa9, 0x07, 0x0e, 0x00, 0x00,
}

func (m *Permission) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Permission) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Permission) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VsOperatorAuthzSpendPeriod != nil {
		n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(*m.VsOperatorAuthzSpendPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.VsOperatorAuthzSpendPeriod):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintTypes(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xd2
	}
	if len(m.VsOperatorAuthzFeeSpendLimit) > 0 {
		for iNdEx := len(m.VsOperatorAuthzFeeSpendLimit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VsOperatorAuthzFeeSpendLimit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2
			i--
			dAtA[i] = 0xca
		}
	}
	if m.VsOperatorAuthzWithFeegrant {
		i--
		if m.VsOperatorAuthzWithFeegrant {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xc0
	}
	if len(m.VsOperatorAuthzSpendLimit) > 0 {
		for iNdEx := len(m.VsOperatorAuthzSpendLimit) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VsOperatorAuthzSpendLimit[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2
			i--
			dAtA[i] = 0xba
		}
	}
	if m.VsOperatorAuthzEnabled {
		i--
		if m.VsOperatorAuthzEnabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xb0
	}
	if len(m.VsOperator) > 0 {
		i -= len(m.VsOperator)
		copy(dAtA[i:], m.VsOperator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VsOperator)))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xaa
	}
	if m.VerificationFeeDiscount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VerificationFeeDiscount))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0xa0
	}
	if m.IssuanceFeeDiscount != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.IssuanceFeeDiscount))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x98
	}
	if m.VpTermRequested != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.VpTermRequested, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.VpTermRequested):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintTypes(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x92
	}
	if len(m.VpSummaryDigestSri) > 0 {
		i -= len(m.VpSummaryDigestSri)
		copy(dAtA[i:], m.VpSummaryDigestSri)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VpSummaryDigestSri)))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x8a
	}
	if m.VpCurrentDeposit != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VpCurrentDeposit))
		i--
		dAtA[i] = 0x2
		i--
		dAtA[i] = 0x80
	}
	if m.VpCurrentFees != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VpCurrentFees))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf8
	}
	if m.VpValidatorDeposit != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VpValidatorDeposit))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xf0
	}
	if m.VpLastStateChange != nil {
		n3, err3 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.VpLastStateChange, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.VpLastStateChange):])
		if err3 != nil {
			return 0, err3
		}
		i -= n3
		i = encodeVarintTypes(dAtA, i, uint64(n3))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xea
	}
	if m.VpExp != nil {
		n4, err4 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.VpExp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.VpExp):])
		if err4 != nil {
			return 0, err4
		}
		i -= n4
		i = encodeVarintTypes(dAtA, i, uint64(n4))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xe2
	}
	if m.VpState != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VpState))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd8
	}
	if m.ValidatorPermId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ValidatorPermId))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xd0
	}
	if len(m.Country) > 0 {
		i -= len(m.Country)
		copy(dAtA[i:], m.Country)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Country)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xca
	}
	if len(m.RevokedBy) > 0 {
		i -= len(m.RevokedBy)
		copy(dAtA[i:], m.RevokedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RevokedBy)))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xc2
	}
	if m.Revoked != nil {
		n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Revoked, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Revoked):])
		if err5 != nil {
			return 0, err5
		}
		i -= n5
		i = encodeVarintTypes(dAtA, i, uint64(n5))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xba
	}
	if m.RepaidDeposit != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.RepaidDeposit))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xb0
	}
	if m.SlashedDeposit != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SlashedDeposit))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa8
	}
	if m.Deposit != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Deposit))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0xa0
	}
	if m.VerificationFees != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VerificationFees))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x98
	}
	if m.IssuanceFees != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.IssuanceFees))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x90
	}
	if m.ValidationFees != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ValidationFees))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x88
	}
	if m.Modified != nil {
		n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Modified, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Modified):])
		if err6 != nil {
			return 0, err6
		}
		i -= n6
		i = encodeVarintTypes(dAtA, i, uint64(n6))
		i--
		dAtA[i] = 0x1
		i--
		dAtA[i] = 0x82
	}
	if m.EffectiveUntil != nil {
		n7, err7 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.EffectiveUntil, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EffectiveUntil):])
		if err7 != nil {
			return 0, err7
		}
		i -= n7
		i = encodeVarintTypes(dAtA, i, uint64(n7))
		i--
		dAtA[i] = 0x7a
	}
	if m.EffectiveFrom != nil {
		n8, err8 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.EffectiveFrom, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EffectiveFrom):])
		if err8 != nil {
			return 0, err8
		}
		i -= n8
		i = encodeVarintTypes(dAtA, i, uint64(n8))
		i--
		dAtA[i] = 0x72
	}
	if len(m.RepaidBy) > 0 {
		i -= len(m.RepaidBy)
		copy(dAtA[i:], m.RepaidBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.RepaidBy)))
		i--
		dAtA[i] = 0x6a
	}
	if m.Repaid != nil {
		n9, err9 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Repaid, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Repaid):])
		if err9 != nil {
			return 0, err9
		}
		i -= n9
		i = encodeVarintTypes(dAtA, i, uint64(n9))
		i--
		dAtA[i] = 0x62
	}
	if len(m.SlashedBy) > 0 {
		i -= len(m.SlashedBy)
		copy(dAtA[i:], m.SlashedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.SlashedBy)))
		i--
		dAtA[i] = 0x5a
	}
	if m.Slashed != nil {
		n10, err10 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Slashed, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Slashed):])
		if err10 != nil {
			return 0, err10
		}
		i -= n10
		i = encodeVarintTypes(dAtA, i, uint64(n10))
		i--
		dAtA[i] = 0x52
	}
	if len(m.AdjustedBy) > 0 {
		i -= len(m.AdjustedBy)
		copy(dAtA[i:], m.AdjustedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.AdjustedBy)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Adjusted != nil {
		n11, err11 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Adjusted, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Adjusted):])
		if err11 != nil {
			return 0, err11
		}
		i -= n11
		i = encodeVarintTypes(dAtA, i, uint64(n11))
		i--
		dAtA[i] = 0x42
	}
	if len(m.CreatedBy) > 0 {
		i -= len(m.CreatedBy)
		copy(dAtA[i:], m.CreatedBy)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CreatedBy)))
		i--
		dAtA[i] = 0x3a
	}
	if m.Created != nil {
		n12, err12 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Created, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Created):])
		if err12 != nil {
			return 0, err12
		}
		i -= n12
		i = encodeVarintTypes(dAtA, i, uint64(n12))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0x22
	}
	if m.Type != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x18
	}
	if m.SchemaId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.SchemaId))
		i--
		dAtA[i] = 0x10
	}
	if m.Id != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *PermissionSession) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PermissionSession) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PermissionSession) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Modified != nil {
		n13, err13 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Modified, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Modified):])
		if err13 != nil {
			return 0, err13
		}
		i -= n13
		i = encodeVarintTypes(dAtA, i, uint64(n13))
		i--
		dAtA[i] = 0x3a
	}
	if m.Created != nil {
		n14, err14 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Created, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Created):])
		if err14 != nil {
			return 0, err14
		}
		i -= n14
		i = encodeVarintTypes(dAtA, i, uint64(n14))
		i--
		dAtA[i] = 0x32
	}
	if len(m.SessionRecords) > 0 {
		for iNdEx := len(m.SessionRecords) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SessionRecords[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.AgentPermId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.AgentPermId))
		i--
		dAtA[i] = 0x20
	}
	if len(m.VsOperator) > 0 {
		i -= len(m.VsOperator)
		copy(dAtA[i:], m.VsOperator)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.VsOperator)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PermissionSessionRecord) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PermissionSessionRecord) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PermissionSessionRecord) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.WalletAgentPermId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.WalletAgentPermId))
		i--
		dAtA[i] = 0x20
	}
	if m.VerifierPermId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.VerifierPermId))
		i--
		dAtA[i] = 0x18
	}
	if m.IssuerPermId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.IssuerPermId))
		i--
		dAtA[i] = 0x10
	}
	if m.Created != nil {
		n15, err15 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.Created, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Created):])
		if err15 != nil {
			return 0, err15
		}
		i -= n15
		i = encodeVarintTypes(dAtA, i, uint64(n15))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OptionalUInt64) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptionalUInt64) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OptionalUInt64) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Value != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Value))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Permission) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTypes(uint64(m.Id))
	}
	if m.SchemaId != 0 {
		n += 1 + sovTypes(uint64(m.SchemaId))
	}
	if m.Type != 0 {
		n += 1 + sovTypes(uint64(m.Type))
	}
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Created != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Created)
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CreatedBy)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Adjusted != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Adjusted)
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.AdjustedBy)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Slashed != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Slashed)
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.SlashedBy)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Repaid != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Repaid)
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.RepaidBy)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.EffectiveFrom != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EffectiveFrom)
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.EffectiveUntil != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.EffectiveUntil)
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Modified != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Modified)
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.ValidationFees != 0 {
		n += 2 + sovTypes(uint64(m.ValidationFees))
	}
	if m.IssuanceFees != 0 {
		n += 2 + sovTypes(uint64(m.IssuanceFees))
	}
	if m.VerificationFees != 0 {
		n += 2 + sovTypes(uint64(m.VerificationFees))
	}
	if m.Deposit != 0 {
		n += 2 + sovTypes(uint64(m.Deposit))
	}
	if m.SlashedDeposit != 0 {
		n += 2 + sovTypes(uint64(m.SlashedDeposit))
	}
	if m.RepaidDeposit != 0 {
		n += 2 + sovTypes(uint64(m.RepaidDeposit))
	}
	if m.Revoked != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Revoked)
		n += 2 + l + sovTypes(uint64(l))
	}
	l = len(m.RevokedBy)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	l = len(m.Country)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.ValidatorPermId != 0 {
		n += 2 + sovTypes(uint64(m.ValidatorPermId))
	}
	if m.VpState != 0 {
		n += 2 + sovTypes(uint64(m.VpState))
	}
	if m.VpExp != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.VpExp)
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.VpLastStateChange != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.VpLastStateChange)
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.VpValidatorDeposit != 0 {
		n += 2 + sovTypes(uint64(m.VpValidatorDeposit))
	}
	if m.VpCurrentFees != 0 {
		n += 2 + sovTypes(uint64(m.VpCurrentFees))
	}
	if m.VpCurrentDeposit != 0 {
		n += 2 + sovTypes(uint64(m.VpCurrentDeposit))
	}
	l = len(m.VpSummaryDigestSri)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.VpTermRequested != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.VpTermRequested)
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.IssuanceFeeDiscount != 0 {
		n += 2 + sovTypes(uint64(m.IssuanceFeeDiscount))
	}
	if m.VerificationFeeDiscount != 0 {
		n += 2 + sovTypes(uint64(m.VerificationFeeDiscount))
	}
	l = len(m.VsOperator)
	if l > 0 {
		n += 2 + l + sovTypes(uint64(l))
	}
	if m.VsOperatorAuthzEnabled {
		n += 3
	}
	if len(m.VsOperatorAuthzSpendLimit) > 0 {
		for _, e := range m.VsOperatorAuthzSpendLimit {
			l = e.Size()
			n += 2 + l + sovTypes(uint64(l))
		}
	}
	if m.VsOperatorAuthzWithFeegrant {
		n += 3
	}
	if len(m.VsOperatorAuthzFeeSpendLimit) > 0 {
		for _, e := range m.VsOperatorAuthzFeeSpendLimit {
			l = e.Size()
			n += 2 + l + sovTypes(uint64(l))
		}
	}
	if m.VsOperatorAuthzSpendPeriod != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(*m.VsOperatorAuthzSpendPeriod)
		n += 2 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *PermissionSession) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.VsOperator)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.AgentPermId != 0 {
		n += 1 + sovTypes(uint64(m.AgentPermId))
	}
	if len(m.SessionRecords) > 0 {
		for _, e := range m.SessionRecords {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	if m.Created != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Created)
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Modified != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Modified)
		n += 1 + l + sovTypes(uint64(l))
	}
	return n
}

func (m *PermissionSessionRecord) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Created != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.Created)
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.IssuerPermId != 0 {
		n += 1 + sovTypes(uint64(m.IssuerPermId))
	}
	if m.VerifierPermId != 0 {
		n += 1 + sovTypes(uint64(m.VerifierPermId))
	}
	if m.WalletAgentPermId != 0 {
		n += 1 + sovTypes(uint64(m.WalletAgentPermId))
	}
	return n
}

func (m *OptionalUInt64) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Value != 0 {
		n += 1 + sovTypes(uint64(m.Value))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Permission) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Permission: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Permission: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaId", wireType)
			}
			m.SchemaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SchemaId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= PermissionType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Created == nil {
				m.Created = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Created, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Adjusted", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Adjusted == nil {
				m.Adjusted = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Adjusted, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdjustedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AdjustedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Slashed", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Slashed == nil {
				m.Slashed = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Slashed, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Repaid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Repaid == nil {
				m.Repaid = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Repaid, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepaidBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RepaidBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveFrom", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EffectiveFrom == nil {
				m.EffectiveFrom = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.EffectiveFrom, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveUntil", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EffectiveUntil == nil {
				m.EffectiveUntil = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.EffectiveUntil, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Modified", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Modified == nil {
				m.Modified = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Modified, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 17:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidationFees", wireType)
			}
			m.ValidationFees = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidationFees |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 18:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuanceFees", wireType)
			}
			m.IssuanceFees = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuanceFees |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 19:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationFees", wireType)
			}
			m.VerificationFees = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerificationFees |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 20:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Deposit", wireType)
			}
			m.Deposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Deposit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 21:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashedDeposit", wireType)
			}
			m.SlashedDeposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SlashedDeposit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 22:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RepaidDeposit", wireType)
			}
			m.RepaidDeposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RepaidDeposit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 23:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revoked", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Revoked == nil {
				m.Revoked = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Revoked, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 24:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RevokedBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RevokedBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 25:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Country", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Country = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 26:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorPermId", wireType)
			}
			m.ValidatorPermId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValidatorPermId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 27:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VpState", wireType)
			}
			m.VpState = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VpState |= ValidationState(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 28:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VpExp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VpExp == nil {
				m.VpExp = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.VpExp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 29:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VpLastStateChange", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VpLastStateChange == nil {
				m.VpLastStateChange = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.VpLastStateChange, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 30:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VpValidatorDeposit", wireType)
			}
			m.VpValidatorDeposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VpValidatorDeposit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 31:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VpCurrentFees", wireType)
			}
			m.VpCurrentFees = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VpCurrentFees |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 32:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VpCurrentDeposit", wireType)
			}
			m.VpCurrentDeposit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VpCurrentDeposit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 33:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VpSummaryDigestSri", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VpSummaryDigestSri = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 34:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VpTermRequested", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VpTermRequested == nil {
				m.VpTermRequested = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.VpTermRequested, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 35:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuanceFeeDiscount", wireType)
			}
			m.IssuanceFeeDiscount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuanceFeeDiscount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 36:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerificationFeeDiscount", wireType)
			}
			m.VerificationFeeDiscount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerificationFeeDiscount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 37:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VsOperator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VsOperator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 38:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VsOperatorAuthzEnabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.VsOperatorAuthzEnabled = bool(v != 0)
		case 39:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VsOperatorAuthzSpendLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VsOperatorAuthzSpendLimit = append(m.VsOperatorAuthzSpendLimit, types.Coin{})
			if err := m.VsOperatorAuthzSpendLimit[len(m.VsOperatorAuthzSpendLimit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 40:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VsOperatorAuthzWithFeegrant", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.VsOperatorAuthzWithFeegrant = bool(v != 0)
		case 41:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VsOperatorAuthzFeeSpendLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VsOperatorAuthzFeeSpendLimit = append(m.VsOperatorAuthzFeeSpendLimit, types.Coin{})
			if err := m.VsOperatorAuthzFeeSpendLimit[len(m.VsOperatorAuthzFeeSpendLimit)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 42:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VsOperatorAuthzSpendPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.VsOperatorAuthzSpendPeriod == nil {
				m.VsOperatorAuthzSpendPeriod = new(time.Duration)
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(m.VsOperatorAuthzSpendPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PermissionSession) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PermissionSession: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PermissionSession: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VsOperator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VsOperator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AgentPermId", wireType)
			}
			m.AgentPermId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AgentPermId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionRecords", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SessionRecords = append(m.SessionRecords, &PermissionSessionRecord{})
			if err := m.SessionRecords[len(m.SessionRecords)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Created == nil {
				m.Created = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Created, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Modified", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Modified == nil {
				m.Modified = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Modified, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PermissionSessionRecord) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PermissionSessionRecord: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PermissionSessionRecord: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Created == nil {
				m.Created = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.Created, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerPermId", wireType)
			}
			m.IssuerPermId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerPermId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierPermId", wireType)
			}
			m.VerifierPermId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifierPermId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletAgentPermId", wireType)
			}
			m.WalletAgentPermId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.WalletAgentPermId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OptionalUInt64) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptionalUInt64: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptionalUInt64: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			m.Value = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Value |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
