// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: verana/pp/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryListParticipantsRequest struct {
	ModifiedAfter   *time.Time `protobuf:"bytes,1,opt,name=modified_after,json=modifiedAfter,proto3,stdtime" json:"modified_after,omitempty"`
	ResponseMaxSize uint32     `protobuf:"varint,2,opt,name=response_max_size,json=responseMaxSize,proto3" json:"response_max_size,omitempty"`
}

func (m *QueryListParticipantsRequest) Reset()         { *m = QueryListParticipantsRequest{} }
func (m *QueryListParticipantsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListParticipantsRequest) ProtoMessage()    {}
func (*QueryListParticipantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{2}
}
func (m *QueryListParticipantsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListParticipantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListParticipantsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListParticipantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListParticipantsRequest.Merge(m, src)
}
func (m *QueryListParticipantsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListParticipantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListParticipantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListParticipantsRequest proto.InternalMessageInfo

func (m *QueryListParticipantsRequest) GetModifiedAfter() *time.Time {
	if m != nil {
		return m.ModifiedAfter
	}
	return nil
}

func (m *QueryListParticipantsRequest) GetResponseMaxSize() uint32 {
	if m != nil {
		return m.ResponseMaxSize
	}
	return 0
}

type QueryListParticipantsResponse struct {
	Participants []Participant `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants"`
}

func (m *QueryListParticipantsResponse) Reset()         { *m = QueryListParticipantsResponse{} }
func (m *QueryListParticipantsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListParticipantsResponse) ProtoMessage()    {}
func (*QueryListParticipantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{3}
}
func (m *QueryListParticipantsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListParticipantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListParticipantsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListParticipantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListParticipantsResponse.Merge(m, src)
}
func (m *QueryListParticipantsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListParticipantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListParticipantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListParticipantsResponse proto.InternalMessageInfo

func (m *QueryListParticipantsResponse) GetParticipants() []Participant {
	if m != nil {
		return m.Participants
	}
	return nil
}

type QueryGetParticipantRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetParticipantRequest) Reset()         { *m = QueryGetParticipantRequest{} }
func (m *QueryGetParticipantRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetParticipantRequest) ProtoMessage()    {}
func (*QueryGetParticipantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{4}
}
func (m *QueryGetParticipantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetParticipantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetParticipantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetParticipantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetParticipantRequest.Merge(m, src)
}
func (m *QueryGetParticipantRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetParticipantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetParticipantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetParticipantRequest proto.InternalMessageInfo

func (m *QueryGetParticipantRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetParticipantResponse struct {
	Participant Participant `protobuf:"bytes,1,opt,name=participant,proto3" json:"participant"`
}

func (m *QueryGetParticipantResponse) Reset()         { *m = QueryGetParticipantResponse{} }
func (m *QueryGetParticipantResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetParticipantResponse) ProtoMessage()    {}
func (*QueryGetParticipantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{5}
}
func (m *QueryGetParticipantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetParticipantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetParticipantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetParticipantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetParticipantResponse.Merge(m, src)
}
func (m *QueryGetParticipantResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetParticipantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetParticipantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetParticipantResponse proto.InternalMessageInfo

func (m *QueryGetParticipantResponse) GetParticipant() Participant {
	if m != nil {
		return m.Participant
	}
	return Participant{}
}

type QueryGetParticipantSessionRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetParticipantSessionRequest) Reset()         { *m = QueryGetParticipantSessionRequest{} }
func (m *QueryGetParticipantSessionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetParticipantSessionRequest) ProtoMessage()    {}
func (*QueryGetParticipantSessionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{6}
}
func (m *QueryGetParticipantSessionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetParticipantSessionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetParticipantSessionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetParticipantSessionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetParticipantSessionRequest.Merge(m, src)
}
func (m *QueryGetParticipantSessionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetParticipantSessionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetParticipantSessionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetParticipantSessionRequest proto.InternalMessageInfo

func (m *QueryGetParticipantSessionRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetParticipantSessionResponse struct {
	Session *ParticipantSession `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
}

func (m *QueryGetParticipantSessionResponse) Reset()         { *m = QueryGetParticipantSessionResponse{} }
func (m *QueryGetParticipantSessionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetParticipantSessionResponse) ProtoMessage()    {}
func (*QueryGetParticipantSessionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{7}
}
func (m *QueryGetParticipantSessionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetParticipantSessionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetParticipantSessionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetParticipantSessionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetParticipantSessionResponse.Merge(m, src)
}
func (m *QueryGetParticipantSessionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetParticipantSessionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetParticipantSessionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetParticipantSessionResponse proto.InternalMessageInfo

func (m *QueryGetParticipantSessionResponse) GetSession() *ParticipantSession {
	if m != nil {
		return m.Session
	}
	return nil
}

type QueryListParticipantSessionsRequest struct {
	ModifiedAfter   *time.Time `protobuf:"bytes,1,opt,name=modified_after,json=modifiedAfter,proto3,stdtime" json:"modified_after,omitempty"`
	ResponseMaxSize uint32     `protobuf:"varint,2,opt,name=response_max_size,json=responseMaxSize,proto3" json:"response_max_size,omitempty"`
}

func (m *QueryListParticipantSessionsRequest) Reset()         { *m = QueryListParticipantSessionsRequest{} }
func (m *QueryListParticipantSessionsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryListParticipantSessionsRequest) ProtoMessage()    {}
func (*QueryListParticipantSessionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{8}
}
func (m *QueryListParticipantSessionsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListParticipantSessionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListParticipantSessionsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListParticipantSessionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListParticipantSessionsRequest.Merge(m, src)
}
func (m *QueryListParticipantSessionsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryListParticipantSessionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListParticipantSessionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListParticipantSessionsRequest proto.InternalMessageInfo

func (m *QueryListParticipantSessionsRequest) GetModifiedAfter() *time.Time {
	if m != nil {
		return m.ModifiedAfter
	}
	return nil
}

func (m *QueryListParticipantSessionsRequest) GetResponseMaxSize() uint32 {
	if m != nil {
		return m.ResponseMaxSize
	}
	return 0
}

type QueryListParticipantSessionsResponse struct {
	Sessions []ParticipantSession `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions"`
}

func (m *QueryListParticipantSessionsResponse) Reset()         { *m = QueryListParticipantSessionsResponse{} }
func (m *QueryListParticipantSessionsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryListParticipantSessionsResponse) ProtoMessage()    {}
func (*QueryListParticipantSessionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{9}
}
func (m *QueryListParticipantSessionsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryListParticipantSessionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryListParticipantSessionsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryListParticipantSessionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryListParticipantSessionsResponse.Merge(m, src)
}
func (m *QueryListParticipantSessionsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryListParticipantSessionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryListParticipantSessionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryListParticipantSessionsResponse proto.InternalMessageInfo

func (m *QueryListParticipantSessionsResponse) GetSessions() []ParticipantSession {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type QueryFindParticipantsWithDIDRequest struct {
	Did      string     `protobuf:"bytes,1,opt,name=did,proto3" json:"did,omitempty"`
	Role     uint32     `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	SchemaId uint64     `protobuf:"varint,3,opt,name=schema_id,json=schemaId,proto3" json:"schema_id,omitempty"`
	When     *time.Time `protobuf:"bytes,5,opt,name=when,proto3,stdtime" json:"when,omitempty"`
}

func (m *QueryFindParticipantsWithDIDRequest) Reset()         { *m = QueryFindParticipantsWithDIDRequest{} }
func (m *QueryFindParticipantsWithDIDRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFindParticipantsWithDIDRequest) ProtoMessage()    {}
func (*QueryFindParticipantsWithDIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{10}
}
func (m *QueryFindParticipantsWithDIDRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFindParticipantsWithDIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFindParticipantsWithDIDRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFindParticipantsWithDIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFindParticipantsWithDIDRequest.Merge(m, src)
}
func (m *QueryFindParticipantsWithDIDRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFindParticipantsWithDIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFindParticipantsWithDIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFindParticipantsWithDIDRequest proto.InternalMessageInfo

func (m *QueryFindParticipantsWithDIDRequest) GetDid() string {
	if m != nil {
		return m.Did
	}
	return ""
}

func (m *QueryFindParticipantsWithDIDRequest) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *QueryFindParticipantsWithDIDRequest) GetSchemaId() uint64 {
	if m != nil {
		return m.SchemaId
	}
	return 0
}

func (m *QueryFindParticipantsWithDIDRequest) GetWhen() *time.Time {
	if m != nil {
		return m.When
	}
	return nil
}

type QueryFindParticipantsWithDIDResponse struct {
	Participants []Participant `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants"`
}

func (m *QueryFindParticipantsWithDIDResponse) Reset()         { *m = QueryFindParticipantsWithDIDResponse{} }
func (m *QueryFindParticipantsWithDIDResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFindParticipantsWithDIDResponse) ProtoMessage()    {}
func (*QueryFindParticipantsWithDIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{11}
}
func (m *QueryFindParticipantsWithDIDResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFindParticipantsWithDIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFindParticipantsWithDIDResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFindParticipantsWithDIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFindParticipantsWithDIDResponse.Merge(m, src)
}
func (m *QueryFindParticipantsWithDIDResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFindParticipantsWithDIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFindParticipantsWithDIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFindParticipantsWithDIDResponse proto.InternalMessageInfo

func (m *QueryFindParticipantsWithDIDResponse) GetParticipants() []Participant {
	if m != nil {
		return m.Participants
	}
	return nil
}

type QueryFindBeneficiariesRequest struct {
	IssuerParticipantId   uint64 `protobuf:"varint,1,opt,name=issuer_participant_id,json=issuerParticipantId,proto3" json:"issuer_participant_id,omitempty"`
	VerifierParticipantId uint64 `protobuf:"varint,2,opt,name=verifier_participant_id,json=verifierParticipantId,proto3" json:"verifier_participant_id,omitempty"`
}

func (m *QueryFindBeneficiariesRequest) Reset()         { *m = QueryFindBeneficiariesRequest{} }
func (m *QueryFindBeneficiariesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFindBeneficiariesRequest) ProtoMessage()    {}
func (*QueryFindBeneficiariesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{12}
}
func (m *QueryFindBeneficiariesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFindBeneficiariesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFindBeneficiariesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFindBeneficiariesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFindBeneficiariesRequest.Merge(m, src)
}
func (m *QueryFindBeneficiariesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFindBeneficiariesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFindBeneficiariesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFindBeneficiariesRequest proto.InternalMessageInfo

func (m *QueryFindBeneficiariesRequest) GetIssuerParticipantId() uint64 {
	if m != nil {
		return m.IssuerParticipantId
	}
	return 0
}

func (m *QueryFindBeneficiariesRequest) GetVerifierParticipantId() uint64 {
	if m != nil {
		return m.VerifierParticipantId
	}
	return 0
}

type QueryFindBeneficiariesResponse struct {
	Participants []Participant `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants"`
}

func (m *QueryFindBeneficiariesResponse) Reset()         { *m = QueryFindBeneficiariesResponse{} }
func (m *QueryFindBeneficiariesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFindBeneficiariesResponse) ProtoMessage()    {}
func (*QueryFindBeneficiariesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_438e2e8e140e775a, []int{13}
}
func (m *QueryFindBeneficiariesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFindBeneficiariesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFindBeneficiariesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFindBeneficiariesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFindBeneficiariesResponse.Merge(m, src)
}
func (m *QueryFindBeneficiariesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFindBeneficiariesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFindBeneficiariesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFindBeneficiariesResponse proto.InternalMessageInfo

func (m *QueryFindBeneficiariesResponse) GetParticipants() []Participant {
	if m != nil {
		return m.Participants
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "verana.pp.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "verana.pp.v1.QueryParamsResponse")
	proto.RegisterType((*QueryListParticipantsRequest)(nil), "verana.pp.v1.QueryListParticipantsRequest")
	proto.RegisterType((*QueryListParticipantsResponse)(nil), "verana.pp.v1.QueryListParticipantsResponse")
	proto.RegisterType((*QueryGetParticipantRequest)(nil), "verana.pp.v1.QueryGetParticipantRequest")
	proto.RegisterType((*QueryGetParticipantResponse)(nil), "verana.pp.v1.QueryGetParticipantResponse")
	proto.RegisterType((*QueryGetParticipantSessionRequest)(nil), "verana.pp.v1.QueryGetParticipantSessionRequest")
	proto.RegisterType((*QueryGetParticipantSessionResponse)(nil), "verana.pp.v1.QueryGetParticipantSessionResponse")
	proto.RegisterType((*QueryListParticipantSessionsRequest)(nil), "verana.pp.v1.QueryListParticipantSessionsRequest")
	proto.RegisterType((*QueryListParticipantSessionsResponse)(nil), "verana.pp.v1.QueryListParticipantSessionsResponse")
	proto.RegisterType((*QueryFindParticipantsWithDIDRequest)(nil), "verana.pp.v1.QueryFindParticipantsWithDIDRequest")
	proto.RegisterType((*QueryFindParticipantsWithDIDResponse)(nil), "verana.pp.v1.QueryFindParticipantsWithDIDResponse")
	proto.RegisterType((*QueryFindBeneficiariesRequest)(nil), "verana.pp.v1.QueryFindBeneficiariesRequest")
	proto.RegisterType((*QueryFindBeneficiariesResponse)(nil), "verana.pp.v1.QueryFindBeneficiariesResponse")
}

func init() { proto.RegisterFile("verana/pp/v1/query.proto", fileDescriptor_438e2e8e140e775a) }

var fileDescriptor_438e2e8e140e775a = []byte{
	// 931 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x96, 0xcf, 0x6f, 0x1b, 0x45,
	0x14, 0xc7, 0x33, 0x8e, 0x93, 0x3a, 0x93, 0x36, 0x24, 0x53, 0xa7, 0x71, 0x37, 0xe9, 0xc6, 0xdd,
	0x22, 0x64, 0xd2, 0xb2, 0x8b, 0x5d, 0x09, 0x10, 0xb7, 0x9a, 0x0a, 0x14, 0x7e, 0xa9, 0xb8, 0x48,
	0x48, 0x5c, 0x96, 0xb1, 0x77, 0x6c, 0x0f, 0xcd, 0xee, 0x6c, 0x77, 0xc6, 0x6e, 0x52, 0xc4, 0x05,
	0x09, 0x71, 0xe0, 0x12, 0xa9, 0x07, 0x6e, 0x1c, 0x10, 0x48, 0x1c, 0xe1, 0xbf, 0xc8, 0xb1, 0x12,
	0x17, 0x4e, 0x05, 0x25, 0x48, 0xfc, 0x1b, 0x68, 0x67, 0x67, 0xa2, 0xdd, 0x78, 0xd7, 0x4e, 0xa5,
	0x4a, 0x5c, 0xa2, 0xcd, 0xcc, 0xfb, 0xbe, 0xf7, 0x79, 0x6f, 0x66, 0xbe, 0x09, 0xac, 0x8d, 0x49,
	0x84, 0x03, 0xec, 0x84, 0xa1, 0x33, 0x6e, 0x3a, 0x0f, 0x47, 0x24, 0x3a, 0xb0, 0xc3, 0x88, 0x09,
	0x86, 0x2e, 0x26, 0x3b, 0x76, 0x18, 0xda, 0xe3, 0xa6, 0xb1, 0x86, 0x7d, 0x1a, 0x30, 0x47, 0xfe,
	0x4c, 0x02, 0x8c, 0x9d, 0x1e, 0xe3, 0x3e, 0xe3, 0x4e, 0x17, 0x73, 0x92, 0x28, 0x9d, 0x71, 0xb3,
	0x4b, 0x04, 0x6e, 0x3a, 0x21, 0x1e, 0xd0, 0x00, 0x0b, 0xca, 0x02, 0x15, 0x5b, 0x1d, 0xb0, 0x01,
	0x93, 0x9f, 0x4e, 0xfc, 0xa5, 0x56, 0xb7, 0x06, 0x8c, 0x0d, 0xf6, 0x88, 0x83, 0x43, 0xea, 0xe0,
	0x20, 0x60, 0x42, 0x4a, 0xb8, 0xda, 0xdd, 0x56, 0xbb, 0xf2, 0xb7, 0xee, 0xa8, 0xef, 0x08, 0xea,
	0x13, 0x2e, 0xb0, 0x1f, 0xaa, 0x80, 0xab, 0x19, 0xf6, 0x10, 0x47, 0xd8, 0xd7, 0xda, 0x6c, 0x5b,
	0xe2, 0x20, 0x24, 0x6a, 0xc7, 0xaa, 0x42, 0xf4, 0x49, 0xcc, 0x7a, 0x4f, 0x86, 0x77, 0xc8, 0xc3,
	0x11, 0xe1, 0xc2, 0xfa, 0x18, 0x5e, 0xce, 0xac, 0xf2, 0x90, 0x05, 0x9c, 0xa0, 0x37, 0xe1, 0x62,
	0x92, 0xb6, 0x06, 0xea, 0xa0, 0xb1, 0xdc, 0xaa, 0xda, 0xe9, 0xa1, 0xd8, 0x49, 0x74, 0x7b, 0xe9,
	0xe8, 0xd9, 0xf6, 0xdc, 0xaf, 0xff, 0xfe, 0xb6, 0x03, 0x3a, 0x2a, 0xdc, 0xfa, 0x01, 0xc0, 0x2d,
	0x99, 0xf0, 0x43, 0xca, 0xc5, 0x3d, 0x1c, 0x09, 0xda, 0xa3, 0x21, 0x0e, 0x84, 0x2e, 0x88, 0x3e,
	0x80, 0x2b, 0x3e, 0xf3, 0x68, 0x9f, 0x12, 0xcf, 0xc5, 0x7d, 0x41, 0x22, 0x55, 0xc1, 0xb0, 0x93,
	0xae, 0x6d, 0xdd, 0xb5, 0xfd, 0xa9, 0xee, 0xba, 0x5d, 0x39, 0x7a, 0xb6, 0x0d, 0x0e, 0xff, 0xda,
	0x06, 0x9d, 0x4b, 0x5a, 0x7b, 0x27, 0x96, 0xa2, 0x1d, 0xb8, 0x16, 0x29, 0x64, 0xd7, 0xc7, 0xfb,
	0x2e, 0xa7, 0x8f, 0x49, 0xad, 0x54, 0x07, 0x8d, 0x4b, 0x9d, 0x97, 0xf4, 0xc6, 0x47, 0x78, 0xff,
	0x3e, 0x7d, 0x4c, 0x2c, 0x0f, 0x5e, 0x2b, 0x00, 0x53, 0x3d, 0xbf, 0x03, 0x2f, 0x86, 0xa9, 0xf5,
	0x1a, 0xa8, 0xcf, 0x37, 0x96, 0x5b, 0x57, 0x27, 0x3a, 0xd7, 0x11, 0xed, 0x72, 0xdc, 0x7e, 0x27,
	0x23, 0xb2, 0x6e, 0x41, 0x43, 0x56, 0x79, 0x8f, 0xa4, 0x8b, 0xe8, 0xe6, 0x57, 0x60, 0x89, 0x7a,
	0xb2, 0xe1, 0x72, 0xa7, 0x44, 0x3d, 0xeb, 0x0b, 0xb8, 0x99, 0x1b, 0xad, 0x88, 0xee, 0xc0, 0xe5,
	0x54, 0x72, 0x35, 0xa8, 0x99, 0x40, 0x69, 0x8d, 0x75, 0x1b, 0x5e, 0xcf, 0xa9, 0x70, 0x9f, 0x70,
	0x4e, 0x59, 0x30, 0x89, 0xb5, 0xa4, 0xb0, 0xac, 0x69, 0x22, 0x45, 0xf7, 0x36, 0xbc, 0xc0, 0x93,
	0x25, 0x45, 0x56, 0x2f, 0x24, 0xd3, 0x52, 0x2d, 0xb0, 0x7e, 0x04, 0xf0, 0x46, 0xde, 0x69, 0xa8,
	0xc0, 0xff, 0xff, 0xb6, 0x7c, 0x09, 0x5f, 0x9e, 0xce, 0xa7, 0x86, 0xd0, 0x86, 0x15, 0xd5, 0x93,
	0xbe, 0x30, 0x33, 0xa7, 0xa0, 0x8e, 0xe9, 0x54, 0x67, 0xfd, 0xae, 0x87, 0xf1, 0x2e, 0x0d, 0xbc,
	0xf4, 0xd5, 0xfc, 0x8c, 0x8a, 0xe1, 0xdd, 0xdd, 0xbb, 0x7a, 0x18, 0xab, 0x70, 0xde, 0x3b, 0x3d,
	0xa7, 0xf8, 0x13, 0x21, 0x58, 0x8e, 0xd8, 0x9e, 0x6e, 0x42, 0x7e, 0xa3, 0x4d, 0xb8, 0xc4, 0x7b,
	0x43, 0xe2, 0x63, 0x97, 0x7a, 0xb5, 0x79, 0x79, 0xd5, 0x2a, 0xc9, 0xc2, 0xae, 0x87, 0xde, 0x82,
	0xe5, 0x47, 0x43, 0x12, 0xd4, 0x16, 0x9e, 0x63, 0x8a, 0x52, 0xf1, 0x7e, 0xb9, 0x52, 0x5e, 0x5d,
	0xe8, 0x5c, 0xe8, 0xb1, 0x51, 0x20, 0xa2, 0x03, 0xeb, 0x81, 0x9a, 0x4f, 0x21, 0xf2, 0x8b, 0x7c,
	0x54, 0xdf, 0x03, 0xf5, 0x76, 0xe3, 0x6a, 0x6d, 0x12, 0x90, 0x3e, 0xed, 0x51, 0x1c, 0x51, 0x72,
	0x7a, 0x4f, 0x5a, 0x70, 0x9d, 0x72, 0x3e, 0x22, 0x91, 0x9b, 0x12, 0xba, 0xa7, 0x6f, 0xed, 0x72,
	0xb2, 0x99, 0xaa, 0xb3, 0xeb, 0xa1, 0x37, 0xe0, 0xc6, 0x98, 0x44, 0xf1, 0xfd, 0x98, 0x50, 0x95,
	0xa4, 0x6a, 0x5d, 0x6f, 0x67, 0x74, 0x16, 0x81, 0x66, 0x11, 0xcc, 0x0b, 0x6c, 0xba, 0x75, 0x58,
	0x81, 0x0b, 0xb2, 0x0e, 0x7a, 0x00, 0x17, 0x13, 0xc3, 0x45, 0x67, 0xee, 0xd6, 0xa4, 0x9f, 0x1b,
	0xd7, 0xa7, 0x44, 0x24, 0x74, 0xd6, 0xd6, 0x37, 0x7f, 0xfc, 0xf3, 0xa4, 0x74, 0x05, 0x55, 0x9d,
	0x9c, 0x3f, 0x23, 0xe8, 0x3b, 0x00, 0x57, 0xcf, 0x5a, 0x24, 0xda, 0xc9, 0xc9, 0x5a, 0x60, 0xf0,
	0xc6, 0xcd, 0x73, 0xc5, 0x2a, 0x16, 0x43, 0xb2, 0x54, 0x11, 0xca, 0xb2, 0xec, 0x51, 0x2e, 0xd0,
	0xb7, 0x00, 0xae, 0x64, 0x1d, 0x08, 0x35, 0x72, 0x72, 0xe7, 0x3a, 0xad, 0xf1, 0xea, 0x39, 0x22,
	0x15, 0x83, 0x29, 0x19, 0x6a, 0xe8, 0x4a, 0x96, 0x61, 0x40, 0x84, 0xf3, 0x15, 0xf5, 0xbe, 0x46,
	0x3f, 0x01, 0xb8, 0x9e, 0xeb, 0x84, 0xc8, 0x99, 0x59, 0x24, 0x6b, 0xb4, 0xc6, 0xeb, 0xe7, 0x17,
	0x28, 0xb8, 0x57, 0x24, 0x5c, 0x1d, 0x99, 0x13, 0x70, 0xae, 0xf2, 0x8f, 0x04, 0xf2, 0x67, 0x00,
	0x37, 0x0a, 0xbc, 0x0a, 0x35, 0x67, 0x9f, 0xc8, 0x19, 0xdf, 0x35, 0x5a, 0xcf, 0x23, 0x51, 0xa8,
	0x96, 0x44, 0xdd, 0x42, 0xc6, 0xe4, 0x59, 0x6a, 0x56, 0xf4, 0x0b, 0x80, 0x1b, 0x05, 0x96, 0x91,
	0x8b, 0x39, 0xdd, 0x11, 0x73, 0x31, 0x67, 0x38, 0x92, 0x75, 0x43, 0x62, 0x5e, 0x43, 0x9b, 0x59,
	0xcc, 0x3e, 0x0d, 0x3c, 0xf7, 0x11, 0x15, 0x43, 0x37, 0x36, 0xd6, 0x27, 0x00, 0xae, 0x4d, 0xbc,
	0x6f, 0x74, 0xb3, 0xa0, 0x5c, 0x9e, 0x25, 0x19, 0xb7, 0xce, 0x17, 0x3c, 0x9d, 0xaa, 0x9b, 0x0e,
	0x6e, 0xb7, 0x8f, 0x8e, 0x4d, 0xf0, 0xf4, 0xd8, 0x04, 0x7f, 0x1f, 0x9b, 0xe0, 0xf0, 0xc4, 0x9c,
	0x7b, 0x7a, 0x62, 0xce, 0xfd, 0x79, 0x62, 0xce, 0x7d, 0xde, 0x18, 0x50, 0x31, 0x1c, 0x75, 0xed,
	0x1e, 0xf3, 0x55, 0x82, 0xd7, 0xf6, 0x70, 0x97, 0xeb, 0x64, 0xfb, 0x71, 0x3a, 0xf9, 0xcf, 0x60,
	0x77, 0x51, 0x7a, 0xfd, 0xed, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xab, 0x53, 0xdb, 0x19, 0x00,
	0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	ListParticipants(ctx context.Context, in *QueryListParticipantsRequest, opts ...grpc.CallOption) (*QueryListParticipantsResponse, error)
	GetParticipant(ctx context.Context, in *QueryGetParticipantRequest, opts ...grpc.CallOption) (*QueryGetParticipantResponse, error)
	GetParticipantSession(ctx context.Context, in *QueryGetParticipantSessionRequest, opts ...grpc.CallOption) (*QueryGetParticipantSessionResponse, error)
	ListParticipantSessions(ctx context.Context, in *QueryListParticipantSessionsRequest, opts ...grpc.CallOption) (*QueryListParticipantSessionsResponse, error)
	FindParticipantsWithDID(ctx context.Context, in *QueryFindParticipantsWithDIDRequest, opts ...grpc.CallOption) (*QueryFindParticipantsWithDIDResponse, error)
	FindBeneficiaries(ctx context.Context, in *QueryFindBeneficiariesRequest, opts ...grpc.CallOption) (*QueryFindBeneficiariesResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/verana.pp.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListParticipants(ctx context.Context, in *QueryListParticipantsRequest, opts ...grpc.CallOption) (*QueryListParticipantsResponse, error) {
	out := new(QueryListParticipantsResponse)
	err := c.cc.Invoke(ctx, "/verana.pp.v1.Query/ListParticipants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetParticipant(ctx context.Context, in *QueryGetParticipantRequest, opts ...grpc.CallOption) (*QueryGetParticipantResponse, error) {
	out := new(QueryGetParticipantResponse)
	err := c.cc.Invoke(ctx, "/verana.pp.v1.Query/GetParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetParticipantSession(ctx context.Context, in *QueryGetParticipantSessionRequest, opts ...grpc.CallOption) (*QueryGetParticipantSessionResponse, error) {
	out := new(QueryGetParticipantSessionResponse)
	err := c.cc.Invoke(ctx, "/verana.pp.v1.Query/GetParticipantSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ListParticipantSessions(ctx context.Context, in *QueryListParticipantSessionsRequest, opts ...grpc.CallOption) (*QueryListParticipantSessionsResponse, error) {
	out := new(QueryListParticipantSessionsResponse)
	err := c.cc.Invoke(ctx, "/verana.pp.v1.Query/ListParticipantSessions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FindParticipantsWithDID(ctx context.Context, in *QueryFindParticipantsWithDIDRequest, opts ...grpc.CallOption) (*QueryFindParticipantsWithDIDResponse, error) {
	out := new(QueryFindParticipantsWithDIDResponse)
	err := c.cc.Invoke(ctx, "/verana.pp.v1.Query/FindParticipantsWithDID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FindBeneficiaries(ctx context.Context, in *QueryFindBeneficiariesRequest, opts ...grpc.CallOption) (*QueryFindBeneficiariesResponse, error) {
	out := new(QueryFindBeneficiariesResponse)
	err := c.cc.Invoke(ctx, "/verana.pp.v1.Query/FindBeneficiaries", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	ListParticipants(context.Context, *QueryListParticipantsRequest) (*QueryListParticipantsResponse, error)
	GetParticipant(context.Context, *QueryGetParticipantRequest) (*QueryGetParticipantResponse, error)
	GetParticipantSession(context.Context, *QueryGetParticipantSessionRequest) (*QueryGetParticipantSessionResponse, error)
	ListParticipantSessions(context.Context, *QueryListParticipantSessionsRequest) (*QueryListParticipantSessionsResponse, error)
	FindParticipantsWithDID(context.Context, *QueryFindParticipantsWithDIDRequest) (*QueryFindParticipantsWithDIDResponse, error)
	FindBeneficiaries(context.Context, *QueryFindBeneficiariesRequest) (*QueryFindBeneficiariesResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) ListParticipants(ctx context.Context, req *QueryListParticipantsRequest) (*QueryListParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListParticipants not implemented")
}
func (*UnimplementedQueryServer) GetParticipant(ctx context.Context, req *QueryGetParticipantRequest) (*QueryGetParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipant not implemented")
}
func (*UnimplementedQueryServer) GetParticipantSession(ctx context.Context, req *QueryGetParticipantSessionRequest) (*QueryGetParticipantSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipantSession not implemented")
}
func (*UnimplementedQueryServer) ListParticipantSessions(ctx context.Context, req *QueryListParticipantSessionsRequest) (*QueryListParticipantSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListParticipantSessions not implemented")
}
func (*UnimplementedQueryServer) FindParticipantsWithDID(ctx context.Context, req *QueryFindParticipantsWithDIDRequest) (*QueryFindParticipantsWithDIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindParticipantsWithDID not implemented")
}
func (*UnimplementedQueryServer) FindBeneficiaries(ctx context.Context, req *QueryFindBeneficiariesRequest) (*QueryFindBeneficiariesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindBeneficiaries not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.pp.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListParticipantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.pp.v1.Query/ListParticipants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListParticipants(ctx, req.(*QueryListParticipantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.pp.v1.Query/GetParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParticipant(ctx, req.(*QueryGetParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetParticipantSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetParticipantSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetParticipantSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.pp.v1.Query/GetParticipantSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetParticipantSession(ctx, req.(*QueryGetParticipantSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ListParticipantSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryListParticipantSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ListParticipantSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.pp.v1.Query/ListParticipantSessions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ListParticipantSessions(ctx, req.(*QueryListParticipantSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FindParticipantsWithDID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFindParticipantsWithDIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FindParticipantsWithDID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.pp.v1.Query/FindParticipantsWithDID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FindParticipantsWithDID(ctx, req.(*QueryFindParticipantsWithDIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FindBeneficiaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFindBeneficiariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FindBeneficiaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verana.pp.v1.Query/FindBeneficiaries",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FindBeneficiaries(ctx, req.(*QueryFindBeneficiariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "verana.pp.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "ListParticipants",
			Handler:    _Query_ListParticipants_Handler,
		},
		{
			MethodName: "GetParticipant",
			Handler:    _Query_GetParticipant_Handler,
		},
		{
			MethodName: "GetParticipantSession",
			Handler:    _Query_GetParticipantSession_Handler,
		},
		{
			MethodName: "ListParticipantSessions",
			Handler:    _Query_ListParticipantSessions_Handler,
		},
		{
			MethodName: "FindParticipantsWithDID",
			Handler:    _Query_FindParticipantsWithDID_Handler,
		},
		{
			MethodName: "FindBeneficiaries",
			Handler:    _Query_FindBeneficiaries_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verana/pp/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryListParticipantsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListParticipantsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListParticipantsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResponseMaxSize != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ResponseMaxSize))
		i--
		dAtA[i] = 0x10
	}
	if m.ModifiedAfter != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ModifiedAfter, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ModifiedAfter):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintQuery(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListParticipantsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListParticipantsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListParticipantsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Participants) > 0 {
		for iNdEx := len(m.Participants) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Participants[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetParticipantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetParticipantRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetParticipantRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetParticipantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetParticipantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetParticipantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Participant.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetParticipantSessionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetParticipantSessionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetParticipantSessionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetParticipantSessionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetParticipantSessionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetParticipantSessionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Session != nil {
		{
			size, err := m.Session.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListParticipantSessionsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListParticipantSessionsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListParticipantSessionsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ResponseMaxSize != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ResponseMaxSize))
		i--
		dAtA[i] = 0x10
	}
	if m.ModifiedAfter != nil {
		n5, err5 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.ModifiedAfter, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ModifiedAfter):])
		if err5 != nil {
			return 0, err5
		}
		i -= n5
		i = encodeVarintQuery(dAtA, i, uint64(n5))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryListParticipantSessionsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryListParticipantSessionsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryListParticipantSessionsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Sessions) > 0 {
		for iNdEx := len(m.Sessions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Sessions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryFindParticipantsWithDIDRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFindParticipantsWithDIDRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFindParticipantsWithDIDRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.When != nil {
		n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.When, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.When):])
		if err6 != nil {
			return 0, err6
		}
		i -= n6
		i = encodeVarintQuery(dAtA, i, uint64(n6))
		i--
		dAtA[i] = 0x2a
	}
	if m.SchemaId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.SchemaId))
		i--
		dAtA[i] = 0x18
	}
	if m.Role != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Role))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Did) > 0 {
		i -= len(m.Did)
		copy(dAtA[i:], m.Did)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Did)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFindParticipantsWithDIDResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFindParticipantsWithDIDResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFindParticipantsWithDIDResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Participants) > 0 {
		for iNdEx := len(m.Participants) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Participants[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryFindBeneficiariesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFindBeneficiariesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFindBeneficiariesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.VerifierParticipantId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.VerifierParticipantId))
		i--
		dAtA[i] = 0x10
	}
	if m.IssuerParticipantId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.IssuerParticipantId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryFindBeneficiariesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFindBeneficiariesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFindBeneficiariesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Participants) > 0 {
		for iNdEx := len(m.Participants) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Participants[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryListParticipantsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ModifiedAfter != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ModifiedAfter)
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ResponseMaxSize != 0 {
		n += 1 + sovQuery(uint64(m.ResponseMaxSize))
	}
	return n
}

func (m *QueryListParticipantsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Participants) > 0 {
		for _, e := range m.Participants {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryGetParticipantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetParticipantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Participant.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetParticipantSessionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetParticipantSessionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Session != nil {
		l = m.Session.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryListParticipantSessionsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ModifiedAfter != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.ModifiedAfter)
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.ResponseMaxSize != 0 {
		n += 1 + sovQuery(uint64(m.ResponseMaxSize))
	}
	return n
}

func (m *QueryListParticipantSessionsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Sessions) > 0 {
		for _, e := range m.Sessions {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryFindParticipantsWithDIDRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Did)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Role != 0 {
		n += 1 + sovQuery(uint64(m.Role))
	}
	if m.SchemaId != 0 {
		n += 1 + sovQuery(uint64(m.SchemaId))
	}
	if m.When != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.When)
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFindParticipantsWithDIDResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Participants) > 0 {
		for _, e := range m.Participants {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryFindBeneficiariesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IssuerParticipantId != 0 {
		n += 1 + sovQuery(uint64(m.IssuerParticipantId))
	}
	if m.VerifierParticipantId != 0 {
		n += 1 + sovQuery(uint64(m.VerifierParticipantId))
	}
	return n
}

func (m *QueryFindBeneficiariesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Participants) > 0 {
		for _, e := range m.Participants {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListParticipantsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListParticipantsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListParticipantsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModifiedAfter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ModifiedAfter == nil {
				m.ModifiedAfter = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ModifiedAfter, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseMaxSize", wireType)
			}
			m.ResponseMaxSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResponseMaxSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListParticipantsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListParticipantsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListParticipantsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participants = append(m.Participants, Participant{})
			if err := m.Participants[len(m.Participants)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetParticipantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetParticipantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetParticipantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetParticipantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetParticipantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetParticipantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Participant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetParticipantSessionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetParticipantSessionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetParticipantSessionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetParticipantSessionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetParticipantSessionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetParticipantSessionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Session", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Session == nil {
				m.Session = &ParticipantSession{}
			}
			if err := m.Session.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListParticipantSessionsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListParticipantSessionsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListParticipantSessionsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ModifiedAfter", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ModifiedAfter == nil {
				m.ModifiedAfter = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.ModifiedAfter, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResponseMaxSize", wireType)
			}
			m.ResponseMaxSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ResponseMaxSize |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryListParticipantSessionsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryListParticipantSessionsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryListParticipantSessionsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sessions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sessions = append(m.Sessions, ParticipantSession{})
			if err := m.Sessions[len(m.Sessions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFindParticipantsWithDIDRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFindParticipantsWithDIDRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFindParticipantsWithDIDRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Did", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Did = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Role", wireType)
			}
			m.Role = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Role |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SchemaId", wireType)
			}
			m.SchemaId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SchemaId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field When", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.When == nil {
				m.When = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.When, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFindParticipantsWithDIDResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFindParticipantsWithDIDResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFindParticipantsWithDIDResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participants = append(m.Participants, Participant{})
			if err := m.Participants[len(m.Participants)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFindBeneficiariesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFindBeneficiariesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFindBeneficiariesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssuerParticipantId", wireType)
			}
			m.IssuerParticipantId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.IssuerParticipantId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VerifierParticipantId", wireType)
			}
			m.VerifierParticipantId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VerifierParticipantId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFindBeneficiariesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFindBeneficiariesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFindBeneficiariesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Participants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Participants = append(m.Participants, Participant{})
			if err := m.Participants[len(m.Participants)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
